Vagrant.configure(2) do |config|
  config.vm.box = "base"
  
  (1 .. 3).each do |i|
    config.vm.define "web#{i}" do |node|
        node.vm.hostname = "web#{i}"
    end
  end
  
  config.vm.define "app1" do |node|
      node.vm.hostname = "app1"
  end
end
