Vagrant.configure(2) do |config|
  config.vm.box = "base"
  
  config.vm.define "vm001" do |node|
    node.vm.hostname = "vm001"
  end

  config.vm.define "vm002" do |node|
    node.vm.hostname = "vm002"
  end
  
  config.vm.define "vm003" do |node|
    node.vm.hostname = "vm003"
  end
end
